# Note that these settings only apply in `production` even when other
# keys are added here.
production:
  delivery_method: <%= ENV.fetch('SMTP_DELIVERY_METHOD', 'smtp') %>
  from_address: <%= ENV.fetch('SMTP_FROM_ADDRESS', 'notifications@localhost')&.to_json %>
  reply_to: <%= ENV.fetch('SMTP_REPLY_TO', nil)&.to_json %>
  return_path: <%= ENV.fetch('SMTP_RETURN_PATH', nil)&.to_json %>
  smtp_settings:
    port: <%= Rails.application.credentials['SMTP_PORT'] %>
    address: <%= Rails.application.credentials['SMTP_ADDRESS'] %>
    user_name: <%= Rails.application.credentials['SMTP_USERNAME'] %>
    password: <%= Rails.application.credentials['SMTP_PASSWORD'] %>
    domain: <%= Rails.application.credentials['SMTP_HOST'] %>
    authentication: "plain"
    enable_starttls_auto: true
    read_timeout: 20
